### ISSUE TITLE
Should support latest version of eslint-plugin-jest as peer dependency

### ISSUE THREAD

**Issue by smackfu** [americanexpress/eslint-config-amex#105]
eslint-plugin-jest released a new major version 26 three months ago, but this package still requires version 24 or 25.

**Comment by marcusrbrown** [comment]
> eslint-plugin-jest released a new major version 26 three months ago, but this package still requires version 24 or 25.

👍🏽 I'll throw in `eslint-plugin-jest-dom` as it's required if you use the presets for Jest. npm v8 will throw errors during install bc the peerDep semver range isn't wide enough to cover the latest major upstream.
