### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by nellyk** [americanexpress/eslint-config-amex#54]
Create a pull request template
an example can be found at https://github.com/americanexpress/one-app/blob/main/.github/pull_request_template.md

This tutorial can be followed

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by SvA1** [comment]
Hi, I'd be happy to help you out with this. Could you assign me to this?

**Comment by nellyk** [comment]
Awesome! assigned, reachout if you have any questions. You can use the above template and update the repository name

**Comment by Patil2099** [comment]
I would love to work on this issue. If this is still open Can I work on this @nellyk?
